name: ca_buyandsell
description: Canada procurement data
pipeline:
  init:
    method: seed
    params:
      urls: 
        - https://buyandsell.gc.ca/cds/public/ocds/tpsgc-pwgsc_ocds_EF-FY-13-14.json
        - https://buyandsell.gc.ca/cds/public/ocds/tpsgc-pwgsc_ocds_EF-FY-14-15.json
        - https://buyandsell.gc.ca/cds/public/ocds/tpsgc-pwgsc_ocds_EF-FY-15-16.json
        - https://buyandsell.gc.ca/cds/public/ocds/tpsgc-pwgsc_ocds_EF-FY-16-17.json
    handle:
      pass: fetch
  fetch:
    method: fetch
    handle:
      pass: store
  store:
    method: directory
    params:
      path: data